src/Entity/Donateur.php
<?php

namespace App\Entity;

use App\Repository\DonateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: DonateurRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Cet email est déjà utilisé')]
class Donateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: Types::GUID)]
    private ?string $id_donateur = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_donateur = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_donateur = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_donateur = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'donateur', targetEntity: Don::class)]
    private Collection $dons;

    public function __construct()
    {
        $this->dons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getIdDonateur(): ?string
    {
        return $this->id_donateur;
    }

    public function setIdDonateur(string $id_donateur): static
    {
        $this->id_donateur = $id_donateur;

        return $this;
    }

    public function getNomDonateur(): ?string
    {
        return $this->nom_donateur;
    }

    public function setNomDonateur(string $nom_donateur): static
    {
        $this->nom_donateur = $nom_donateur;

        return $this;
    }

    public function getPrenomDonateur(): ?string
    {
        return $this->prenom_donateur;
    }

    public function setPrenomDonateur(string $prenom_donateur): static
    {
        $this->prenom_donateur = $prenom_donateur;

        return $this;
    }

    public function getContactDonateur(): ?string
    {
        return $this->contact_donateur;
    }

    public function setContactDonateur(string $contact_donateur): static
    {
        $this->contact_donateur = $contact_donateur;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Don>
     */
    public function getDons(): Collection
    {
        return $this->dons;
    }

    public function addDon(Don $don): static
    {
        if (!$this->dons->contains($don)) {
            $this->dons->add($don);
            $don->setDonateur($this);
        }

        return $this;
    }

    public function removeDon(Don $don): static
    {
        if ($this->dons->removeElement($don)) {
            // set the owning side to null (unless already changed)
            if ($don->getDonateur() === $this) {
                $don->setDonateur(null);
            }
        }

        return $this;
    }

    public function isAdmin(){
        return in_array('ROLE_ADMIN', $this->getRoles());
    }
}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use App\Entity\Don;
use App\Form\ContactFormType;
use App\Form\DonateurFormType;
use App\Form\DonFormType;
use App\Form\NewsletterFormType;
use App\Repository\CauseRepository;
use App\Repository\DonateurRepository;
use App\Repository\DonRepository;
use App\Repository\NewsletterRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Notifier\TexterInterface;
use Symfony\Component\Routing\Annotation\Route;

class HomePageController extends AbstractController
{
    private $entityManager;
    private $causeRepository;
    private $donRepository;
    private $donateurRepository;
    private $newsletterRepository;

    public function __construct(EntityManagerInterface $entityManager, CauseRepository $causeRepository, DonRepository $donRepository, DonateurRepository $donateurRepository, NewsletterRepository $newsletterRepository)
    {
        $this->entityManager = $entityManager;
        $this->causeRepository = $causeRepository;
        $this->donRepository = $donRepository;
        $this->donateurRepository = $donateurRepository;
        $this->newsletterRepository = $newsletterRepository;
    }

    #[Route('', name: 'app_home_page')]
    public function index(Request $request, TexterInterface $texter): Response
    {
        $count = count($this->causeRepository->findBy(['archive' => false]));
        $nombre_pages = $count % 3 == 0 ? intdiv($count, 3) : intdiv($count, 3) + 1;
        
        $page_actuel = isset($_GET['page']) ? $_GET['page'] : 1;
        
        $causesSet = $this->causeRepository->findBy(['archive' => false], [], 3, 3*($page_actuel -1));
        
        $causes = [];

        foreach ($causesSet as $cause) {
            $total = 0;
            foreach ($cause->getDons() as $don) {
                if ($don->getStatut() == "completed") $total += $don->getMontant();
            }

            $pourcentage = round(($total /$cause->getObjectifCause()), 2);

            $causes[] = [
                'id_cause' => $cause->getIdCause(),
                'nom_cause' => $cause->getNomCause(),
                'description_cause' => $cause->getDescripionCause(),
                'objectif_cause' => $cause->getObjectifCause(),
                'total_cause' => $total,
                'image_cause' => $cause->getImageCause(),
                'pourcentage' => $pourcentage
            ];
        }

        $nbre_donateurs = count($this->donateurRepository->findAll());
        
        $objectifTotal = 0;
        $recolteTotale = 0;

        foreach ($this->causeRepository->findAll() as $cause) {
            $objectifTotal += $cause->getObjectifCause();
        }

        foreach ($this->donRepository->findBy(['statut' => 'completed']) as $don) {
            $recolteTotale += $don->getMontant();
        }
        
        $newsletterForm = $this->createForm(NewsletterFormType::class);
        $newsletterForm->handleRequest($request);
        
        if ($newsletterForm->isSubmitted() && $newsletterForm->isValid()) { 
            if(!$this->newsletterRepository->findOneBy(['email' => $newsletterForm->get('email')->getData()])){
                $newsletter = $newsletterForm->getData();
                
                $this->entityManager->persist($newsletter);
                $this->entityManager->flush();
                
                return $this->redirectToRoute('app_home_page');
            }
        }
        
        if (!$this->getUser()->isVerified()) return $this->render('registration/verification.html.twig', [
            'newsletterForm' => $newsletterForm->createView()
        ]);

        $contactForm = $this->createForm(ContactFormType::class, null, [
            'action' => $this->generateUrl('app_handle_contact')
        ]);

        return $this->render('home_page/index.html.twig', [
            'causes' => $causes,
            'causesTotales' => $count,
            'nbreDonateurs' => $nbre_donateurs,
            'objectifTotale' => $objectifTotal,
            'recolteTotale' => $recolteTotale,
            'statut_page' => [
                'page_actuel' => $page_actuel,
                'nbre_pages' => $nombre_pages
            ],
            'newsletterForm' => $newsletterForm->createView(),
            'contactForm' => $contactForm->createView()
        ]);
    }

    #[Route('/cause/{id_cause}', name:"app_cause_details")]
    public function detailsCause(Request $request, string $id_cause){
        $cause = $this->causeRepository->findOneBy(['id_cause' => $id_cause]);

        $total = 0;
        foreach ($cause->getDons() as $don) {
            if ($don->getStatut() == "completed") $total += $don->getMontant();
        }

        $pourcentage = round(($total /$cause->getObjectifCause()), 2);

        $newDon = new Don();

        $donForm = $this->createForm(DonFormType::class, $newDon, [
            'action' => $this->generateUrl('app_cause_donner', ['id_cause' => $id_cause])
        ]);

        $donsSet = $this->donRepository->findBy(['cause' => $cause, 'statut' => "completed"], ['date_heure' => "DESC"], 10);

        $donsRecents = [];

        foreach ($donsSet as $don){
            $donsRecents[] = [
                'donateur' => $don->getDonateur()->getPrenomDonateur() . " " . $don->getDonateur()->getNomDonateur(),
                'montant' => $don->getMontant(),
                'date_heure' => $don->getDateHeure()
            ];
        }

        $newsletterForm = $this->createForm(NewsletterFormType::class);
        $newsletterForm->handleRequest($request);
        
        if ($newsletterForm->isSubmitted() && $newsletterForm->isValid()) { 
            if(!$this->newsletterRepository->findOneBy(['email' => $newsletterForm->get('email')->getData()])){
                $newsletter = $newsletterForm->getData();

                $this->entityManager->persist($newsletter);
                $this->entityManager->flush();

                return $this->redirectToRoute('app_cause_details', ['id_cause' => $id_cause]);
            }
        }

        if (!$this->getUser()->isVerified()) return $this->render('registration/verification.html.twig', [
            'newsletterForm' => $newsletterForm->createView()
        ]);

        return $this->render("home_page/detailsCause.html.twig", [
            'cause' => [
                'id_cause' => $cause->getIdCause(),
                'nom_cause' => $cause->getNomCause(),
                'description_cause' => $cause->getDescripionCause(),
                'objectif_cause' => $cause->getObjectifCause(),
                'image_cause' => $cause->getImageCause(),
                'recolte_cause' => $total,
                'pourcentage' => $pourcentage
            ],
            'donForm' => $donForm->createView(),
            'donsRecents' => $donsRecents,
            'newsletterForm' => $newsletterForm->createView(),
        ]);
    }

    #[Route('infos', name:"app_infos")]
    public function infos(Request $request){
        $count = count($this->causeRepository->findBy(['archive' => false]));
        $nbre_donateurs = count($this->donateurRepository->findAll());
        $objectifTotal = 0;
        $recolteTotale = 0;

        foreach ($this->causeRepository->findAll() as $cause) {
            $objectifTotal += $cause->getObjectifCause();
        }

        foreach ($this->donRepository->findBy(['statut' => 'completed']) as $don) {
            $recolteTotale += $don->getMontant();
        }

        $newsletterForm = $this->createForm(NewsletterFormType::class);
        $newsletterForm->handleRequest($request);
        
        if ($newsletterForm->isSubmitted() && $newsletterForm->isValid()) { 
            if(!$this->newsletterRepository->findOneBy(['email' => $newsletterForm->get('email')->getData()])){
                $newsletter = $newsletterForm->getData();

                $this->entityManager->persist($newsletter);
                $this->entityManager->flush();

                return $this->redirectToRoute('app_infos');
            }
        }

        if (!$this->getUser()->isVerified()) return $this->render('registration/verification.html.twig', [
            'newsletterForm' => $newsletterForm->createView()
        ]);

        return $this->render("home_page/infos.html.twig", [
            'causesTotales' => $count,
            'nbreDonateurs' => $nbre_donateurs,
            'objectifTotale' => $objectifTotal,
            'recolteTotale' => $recolteTotale,
            'newsletterForm' => $newsletterForm->createView(),
        ]);
    }

    #[Route('/causes', name:"app_causes")]
    public function causes(Request $request){
        $count = count($this->causeRepository->findBy(['archive' => false]));
        $nombre_pages = $count % 3 == 0 ? intdiv($count, 3) : intdiv($count, 3) + 1;

        $page_actuel = isset($_GET['page']) ? $_GET['page'] : 1;

        $causesSet = $this->causeRepository->findBy(['archive' => false], [], 3, 3*($page_actuel -1));

        $causes = [];

        foreach ($causesSet as $cause) {
            $total = 0;
            foreach ($cause->getDons() as $don) {
                if ($don->getStatut() == "completed") $total += $don->getMontant();
            }

            $pourcentage = round(($total /$cause->getObjectifCause()), 2);

            $causes[] = [
                'id_cause' => $cause->getIdCause(),
                'nom_cause' => $cause->getNomCause(),
                'description_cause' => $cause->getDescripionCause(),
                'objectif_cause' => $cause->getObjectifCause(),
                'total_cause' => $total,
                'image_cause' => $cause->getImageCause(),
                'pourcentage' => $pourcentage
            ];
        }

templates/home_page/causes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Songré - Causes{% endblock %}

{% block body %}
    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Causes populaires</h2>
                </div>
                <div class="col-12">
                    <a href="{{path('app_home_page')}}">Accueil</a>
                    <a href="">Causes</a> 
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <div class="causes">
        <div class="container">
            <div class="section-header text-center">
                <p>Nos causes populaires</p>
                <h2>Découvrez ce qui nous tiens vraiment à coeur</h2>
            </div>

            <div class="row" style="margin-bottom : 5vh">
                <div class="col-12 d-flex justify-content-between">
                    <div class="effectif"><strong>Total :</strong> {{total}}</div>
                </div>
            </div>

            {% if causes|length %}
                    <div class="owl-carousel causes-carousel">
                        {% for cause in causes %}
                            <div class="causes-item">
                                <div class="causes-img">
                                    <img src="{{asset(cause.image_cause)}}" alt="Image">
                                </div>
                                <div class="causes-progress">
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="{{cause.pourcentage}}" aria-valuemin="0" aria-valuemax="100">
                                            <span>{{cause.total_cause}}%</span>
                                        </div>
                                    </div>
                                    <div class="progress-text">
                                        <p><strong>Recolté:</strong> {{cause.total_cause}}Fcfa</p>
                                        <p><strong>Objectif:</strong> {{cause.objectif_cause}}Fcfa</p>
                                    </div>
                                </div>
                                <div class="causes-text">
                                    <h3>{{cause.nom_cause}}</h3>
                                    <p>{{cause.description_cause}}</p>
                                </div>
                                <div class="causes-btn">
                                    <a href="{{path('app_cause_details', {'id_cause' : cause.id_cause})}}" class="btn btn-custom">Détails</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    {% if statut_page.nbre_pages > 1  %}
                            <div class="row" style='margin-top : 5vh'>
                                <form action="" method="get" class="col-12 d-flex justify-content-center align-items-center gap-2" id='paginationForm'>
                                    {% if statut_page.page_actuel > 1 %}
                                        <span class=' btn btn-custom' role='button' id='precedent'>
                                            <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
                                            Précédent
                                        </span>
                                    {% endif %}

                                    <input type="number" name="page" id="page" value="{{statut_page.page_actuel}}" class='btn border-secondary' style='width: 60px' min='1' max='{{statut_page.nbre_pages}}'>

                                    {% if statut_page.page_actuel < statut_page.nbre_pages %}
                                        <span class=' btn btn-custom' role='button' id='suivant'>
                                            Suivant
                                            <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                                        </span>
                                    {% endif %}
                                </form>
                            </div>
                    {% endif %}
                {% else %}
                    <h2 class="text-center">Vous n'avez pas encore ajouté de causes</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/home_page/compte.html.twig
{% extends 'base.html.twig' %}

{% block title %}Songré - Compte{% endblock %}


{% block body %}
    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Votre compte</h2>
                </div>
                <div class="col-12">
                    <a href="{{path('app_home_page')}}">Accueil</a>
                    <a href="">Compte</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

     <!-- Volunteer Start -->
        <div class="container">
            <div class="volunteer" data-parallax="scroll" data-image-src="img/volunteer.jpg">
                <div class="row align-items-center">
                    <div class="col-lg-5">
                        <div class="volunteer-form">
                            <div class="control-group">
                                <label for="" class='form-label'>Nom & Prénom</label>
                                <input type="text" class="form-control" value="{{donateur.nom}} {{donateur.prenom}}" required="required" disabled />
                            </div>
                            <div class="control-group">
                                <label for="" class='form-label'>Email</label>
                                <input type="email" class="form-control" value="{{donateur.email}}" required="required" disabled />
                            </div>
                            <div class="control-group">
                                <label for="" class='form-label'>Contact</label>
                                <input type="email" class="form-control" value="{{donateur.contact}}" required="required" disabled />
                            </div>

                            <div class="control-group">
                                <button class="btn btn-custom" data-bs-toggle='modal' data-bs-target="#donateur-modal">Modifier les infos</button>
                            </div>

                            <div>
                                <a href="{{path('app_forgot_password_request')}}"><button class="btn btn-custom">Modifier le mot de passe</button></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-7">
                        <div class="volunteer-content">
                            <div class="section-header">
                                <p>Félicitations à vous</p>
                                <h2>Nous sommes heureux de vous comptez parmi nos donateurs</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Volunteer End -->

        <div class="">
        <div class="container">
            <div class="section-header text-center">
                <h2>Historique de vos dons</h2>
            </div>

            <div class="row" style="margin-bottom : 5vh">
                <div class="col-12 d-flex justify-content-between">
                    <div class="effectif"><strong>Total de vos dons :</strong> {{total}} Fcfa</div>
                </div>
            </div>

            {% if dons|length %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope='col'>Cause</th>
                            <th scope="col">Montant</th>
                            <th scope='col'>Statut</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for don in dons %}
                            <tr data-bs-toggle="modal" data-bs-target='#a{{don.id_don}}'>
                                <th scope="row">{{don.date_heure|date('d/m/Y')}}</th>
                                <th>{{don.cause}}</th>
                                <td>{{don.montant}} Fcfa</td>
                                <td>
                                    {% if don.statut=="completed" %}
                                            Effectué
                                        {% else %}
                                            Annulé
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                    
                {% else %}
                    <h2 class="text-center">Vous n'avez pas encore fait de dons</h2>
            {% endif %}
        </div>

        {% if statut_page.nbre_pages > 1  %}
            <div class="row" style='margin-top : 5vh'>
                <form action="" method="get" class="col-12 d-flex justify-content-center align-items-center gap-2" id='paginationForm'>
                    {% if statut_page.page_actuel > 1 %}
                        <span class=' btn btn-custom' role='button' id='precedent'>
                            <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
                            Précédent
                        </span>
                    {% endif %}

                    <input type="number" name="page" id="page" value="{{statut_page.page_actuel}}" class='btn border-secondary' style='width: 60px' min='1' max='{{statut_page.nbre_pages}}'>

                    {% if statut_page.page_actuel < statut_page.nbre_pages %}
                        <span class=' btn btn-custom' role='button' id='suivant'>
                            Suivant
                            <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                        </span>
                    {% endif %}
                </form>
            </div>
        {% endif %}
    </div>

        <div class="modal fade" id="donateur-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Modifier vos informations personnelles</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {{ form_start(donateurForm) }}
                        <div class="modal-body">
                            {{ form_row(donateurForm.nom_donateur) }}
                            {{ form_row(donateurForm.prenom_donateur) }}
                            {{ form_row(donateurForm.contact_donateur) }}
                        </div>
                        <div class="modal-footer">
                            <input type='submit' class="btn btn-custom" value='Modifier'>
                        </div>
                    {{ form_end(donateurForm) }}
                </div>
            </div>
        </div>

        {% for don in dons %}
        <div class="modal fade" id="a{{don.id_don}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Détails du don</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <label for="" class='form-label'>Identifiant du don</label>
                        <input type="text" name="" id="" class='form-control border-0' value="{{don.id_transaction}}" disabled>

                        <label for="" class='form-label'>Date et heure</label>
                        <input type="text" name="" id="" class='form-control border-0' value="{{don.date_heure|date('d/m/Y')}} à {{don.date_heure|date('H:i:s')}}" disabled>

                        <label for="" class='form-label'>Cause</label>
                        <input type="text" name="" id="" class='form-control border-0' value="{{don.cause}}" disabled>

                        <label for="" class='form-label'>Montant</label>
                        <input type="text" name="" id="" class='form-control border-0' value="{{don.montant}} Fcfa" disabled>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-custom" data-bs-dismiss="modal" aria-label="Close">OK</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/home_page/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Songré - Contact{% endblock %}

{% block body %}
    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Contactez nous</h2>
                </div>
                <div class="col-12">
                    <a href="{{path('app_home_page')}}">Accueil</a>
                    <a href="">Contact</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

<!-- Contact Start -->
<div class="contact">
    <div class="container">
        <div class="section-header text-center">
            <p>Contactez nous</p>
            <h2>Posez nous vos questions</h2>
        </div>
        <div class="contact-img">
            <img src="img/contact.jpg" alt="Image">
        </div>
        <div class="contact-form">
            <div id="success"></div>
            {{ form_start(contactForm) }}
                <div class="control-group mb-3">
                    {{ form_row(contactForm.sujet) }}
                </div>
                <div class="control-group mb-3">
                    {{ form_row(contactForm.message) }}
                </div>
                <div>
                    <button class="btn btn-custom" type="submit" id="sendMessageButton">Envoyer le message</button>
                </div>
            {{ form_end(contactForm) }}
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock %}

templates/home_page/handlecontact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Songré - Contact{% endblock %}

{% block body %}
    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Contactez nous</h2>
                </div>
                <div class="col-12">
                    <a href="{{path('app_home_page')}}">Accueil</a>
                    <a href="">Contact</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <h4 class='text-center'>Merci de nous avoir contacté !!! C'est avec un plaisir que nous répondrons à votre message.</h4>
{% endblock %}

templates/home_page/mailContact.html.twig
<p>{{message}}</p>

<p>Cordialement <b>{{app.user.prenomDonateur}} {{app.user.nomDonateur}}</b> <br>{{app.user.email}}</p>

templates/home_page/paiementEmail.html.twig
<p>Vous venez d'effectuer un don de {{montant}}Fcfa pour la cause "<b>{{cause}}</b>" !!!</p>
<p>Toute l'équipe de Songré vous remercie infiniment pour ce geste !!!</p>
<br>
<p>Cordialement </p>

templates/home_page/paiementStatut.html.twig
{% extends 'base.html.twig' %}

{% block title %}Songré - Paiement{% endblock %}

{% block body %}
    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>{{cause.nom_cause}}</h2>
                </div>
                <div class="col-12">
                    <a href="{{path('app_home_page')}}">Accueil</a>
                    <a href="{{path('app_causes')}}">Causes</a>
                    <a href="{{path('app_cause_details', {'id_cause' : cause.id_cause})}}">Détails</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <h4 class='text-center'>Toute l'équipe de Songré vous remercie infiniment pour votre don !!!</h4>
{% endblock %}